default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: unicode
  username: postgres
  password: postgres

development:
  <<: *default
  database: course-grades_development


test:
  <<: *default
  adapter: postgresql
  database: course-grades_test

production:
  <<: *default
  database: course-grades_production
